services:
  idl-helper:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: idl-helper:latest
    working_dir: /workspace
    volumes:
      - ..:/workspace
    tty: true