services:
  idl:
    platform: linux/amd64
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: idl-dev:latest
    working_dir: /workspace
    volumes:
      - ..:/workspace
    tty: true
